services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: dog-care-nginx
    depends_on:
      - php
    environment:
      HOST: localhost
      PORT: ${APP_PORT:-80}
      PHP_HOST: dog-care-php
      PHP_PORT: 9000
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - './public:/var/www/html/public'
  php:
    build:
      context: docker/php
      args:
        USER_NAME: ${USER_NAME:-user}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: dog-care-php
    depends_on:
      - mysql
    environment:
      XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST:-host.docker.internal}
      XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT:-9003}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=Docker}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${PHP_PORT:-9000}:9000
    volumes:
      - '.:/var/www/html'
  mysql:
    container_name: dog-care-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-dog-care}
      MYSQL_DATABASE: ${DB_NAME:-dog-care}
      MYSQL_USER: ${DB_USER:-dog-care}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dog-care}
    image: mysql:8.2.0
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - 'dog-care-db:/var/lib/mysql'
volumes:
  dog-care-db:
